import React, { useState, useMemo } from 'react';
import {
  X,
  ShieldCheck,
  CheckCircle2,
  AlertCircle,
  Printer,
  Sparkles,
  RefreshCw,
  AlertTriangle,
  FileText
} from 'lucide-react';
import { Language, PTWItem } from '../types';
import { calculateSystemCompliance } from '../utils/complianceEngine';
import { apiService } from '../services/apiService';

interface AuditModalProps {
  language: Language;
  isOpen: boolean;
  onClose: () => void;
  permits: Record<string, PTWItem>;
  onShowToast: (msg: string, type: 'info' | 'success' | 'error') => void;
}

export const AuditModal: React.FC<AuditModalProps> = ({
  language,
  isOpen,
  onClose,
  permits,
  onShowToast,
}) => {
  const [aiReport, setAiReport] = useState<{
    executiveSummaryEn: string;
    executiveSummaryAr: string;
    keyFindingsEn: string[];
    keyFindingsAr: string[];
    complianceScore: number;
    source: string;
  } | null>(null);
  const [isGeneratingAi, setIsGeneratingAi] = useState(false);

  // Real Compliance calculations based on current live permits data
  const compliance = useMemo(() => {
    return calculateSystemCompliance(permits);
  }, [permits]);

  if (!isOpen) return null;

  const handleGenerateAiSummary = async () => {
    setIsGeneratingAi(true);
    onShowToast(
      language === 'ar' ? 'جارٍ استدعاء Gemini لتحليل تقرير الامتثال...' : 'Requesting Gemini AI Audit Summary...',
      'info'
    );
    try {
      const summary = await apiService.generateAuditSummary();
      setAiReport(summary);
      onShowToast(
        language === 'ar' ? 'تم إنشاء التقرير التنفيذي للسلامة بنجاح!' : 'Executive Safety Audit generated by AI!',
        'success'
      );
    } catch (err: any) {
      onShowToast(err.message || 'AI generation failed', 'error');
    } finally {
      setIsGeneratingAi(false);
    }
  };

  const getScoreBadgeColor = (score: number) => {
    if (score >= 90) return 'text-emerald-400 border-emerald-500/50 bg-emerald-950/40';
    if (score >= 70) return 'text-amber-400 border-amber-500/50 bg-amber-950/40';
    return 'text-rose-400 border-rose-500/50 bg-rose-950/40';
  };

  return (
    <div
      onClick={onClose}
      className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-3 lg:p-6 overflow-y-auto"
    >
      <div
        onClick={(e) => e.stopPropagation()}
        className="relative w-full max-w-4xl rounded-2xl bg-[#0b1324] border border-[#1c2b4c] shadow-2xl overflow-hidden flex flex-col max-h-[90vh] my-auto animate-in zoom-in-95 duration-200"
      >
        {/* Header */}
        <div className="p-4 lg:p-5 bg-gradient-to-r from-[#101b33] to-[#0b1324] border-b border-[#1c2b4c] flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-emerald-950 border border-emerald-500/40 flex items-center justify-center text-emerald-400">
              <ShieldCheck className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base lg:text-lg font-bold text-white">
                  {language === 'ar'
                    ? 'سجل التدقيق والامتثال الفعلي لمعايير السلامة (ISO / OSHA / API)'
                    : 'Real-Time Safety Audit & Compliance Engine (ISO / OSHA / API)'}
                </h3>
                <span
                  className={`text-[10px] font-mono px-2 py-0.5 rounded font-bold border ${getScoreBadgeColor(
                    compliance.overallScore
                  )}`}
                >
                  {compliance.overallScore}% {compliance.overallScore >= 90 ? 'AUDIT READY' : 'ACTION REQUIRED'}
                </span>
              </div>
              <p className="text-xs text-[#9fb3c8] font-mono mt-0.5">
                Zubair Field Operating Division (ZFOD) • {compliance.totalPermitsEvaluated} Live Permits Evaluated
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => {
                onShowToast(language === 'ar' ? 'جارٍ إعداد تقرير التدقيق للطباعة...' : 'Printing audit report...', 'info');
                setTimeout(() => window.print(), 400);
              }}
              className="p-2 rounded-lg bg-[#101b33] hover:bg-[#152445] text-slate-200 border border-[#1c2b4c] text-xs font-semibold flex items-center gap-1.5 transition cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5 text-cyan-400" />
              <span>{language === 'ar' ? 'طباعة' : 'Print'}</span>
            </button>
            <button
              onClick={onClose}
              className="w-9 h-9 rounded-lg bg-[#101b33] hover:bg-rose-900/80 hover:text-white text-slate-400 border border-[#1c2b4c] flex items-center justify-center transition cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="p-5 lg:p-6 space-y-5 overflow-y-auto bg-[#060b14] text-xs">
          {/* Dynamic Score Summary Banner */}
          <div
            className={`p-4 rounded-xl border flex items-center justify-between gap-4 flex-wrap ${
              compliance.overallScore >= 90
                ? 'bg-emerald-950/30 border-emerald-500/40'
                : compliance.overallScore >= 70
                ? 'bg-amber-950/30 border-amber-500/40'
                : 'bg-rose-950/30 border-rose-500/40'
            }`}
          >
            <div className="space-y-1 max-w-xl">
              <span className="font-bold flex items-center gap-2 text-sm text-white">
                {compliance.overallScore >= 90 ? (
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                ) : (
                  <AlertTriangle className="w-4 h-4 text-amber-400" />
                )}
                {language === 'ar' ? compliance.overallStatusAr : compliance.overallStatusEn}
              </span>
              <p className="text-slate-300 text-xs leading-relaxed">
                {language === 'ar'
                  ? `تم حساب درجة الامتثال بناءً على ${compliance.totalChecklistsEvaluated} بند تدقيق سلامة (${compliance.checklistPassRate}%)، و${compliance.totalGasTestsEvaluated} فحص غاز معتمد (${compliance.gasSafetyRate}%)، و${compliance.totalSignaturesEvaluated} مصادقة رقمية (${compliance.signatureCompletionRate}%).`
                  : `Calculated from ${compliance.totalChecklistsEvaluated} checklist items (${compliance.checklistPassRate}%), ${compliance.totalGasTestsEvaluated} atmospheric gas samples (${compliance.gasSafetyRate}%), and ${compliance.totalSignaturesEvaluated} digital approvals (${compliance.signatureCompletionRate}%).`}
              </p>
            </div>
            <div className="font-mono text-center px-4 py-2 rounded-lg bg-[#0b1324] border border-[#1c2b4c]">
              <span className="text-[10px] text-[#627d98] block uppercase">Live Score</span>
              <span
                className={`text-2xl font-black ${
                  compliance.overallScore >= 90
                    ? 'text-emerald-400'
                    : compliance.overallScore >= 70
                    ? 'text-amber-400'
                    : 'text-rose-400'
                }`}
              >
                {compliance.overallScore}%
              </span>
            </div>
          </div>

          {/* AI Summary Section */}
          <div className="p-4 rounded-xl bg-[#0b1324] border border-cyan-500/40 space-y-3">
            <div className="flex items-center justify-between flex-wrap gap-2">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-cyan-400 animate-pulse" />
                <span className="font-bold text-white text-xs">
                  {language === 'ar'
                    ? 'ملخص التدقيق الذكي عبر Gemini AI (حقيقي)'
                    : 'Gemini AI Executive Audit Summary (Server-Side)'}
                </span>
                {aiReport && (
                  <span className="px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 text-[10px] font-mono border border-cyan-800">
                    {aiReport.source}
                  </span>
                )}
              </div>
              <button
                onClick={handleGenerateAiSummary}
                disabled={isGeneratingAi}
                className="px-3 py-1.5 rounded-lg bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white font-bold transition flex items-center gap-1.5 cursor-pointer disabled:opacity-50 text-xs shadow-md"
              >
                {isGeneratingAi ? (
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                ) : (
                  <Sparkles className="w-3.5 h-3.5" />
                )}
                <span>
                  {language === 'ar'
                    ? isGeneratingAi
                      ? 'جارٍ التحليل بالذكاء الاصطناعي...'
                      : 'توليد تقرير التدقيق بـ Gemini'
                    : isGeneratingAi
                    ? 'Analyzing with Gemini...'
                    : 'Generate AI Audit Report'}
                </span>
              </button>
            </div>

            {aiReport ? (
              <div className="space-y-3 pt-2 border-t border-[#1c2b4c]">
                <p className="text-slate-200 leading-relaxed font-sans text-xs bg-[#101b33] p-3 rounded-lg border border-[#1c2b4c]">
                  {language === 'ar' ? aiReport.executiveSummaryAr : aiReport.executiveSummaryEn}
                </p>
                <div>
                  <span className="text-[11px] font-bold text-cyan-300 block mb-1">
                    {language === 'ar' ? 'النتائج والملاحظات المحورية:' : 'Key Operational Findings:'}
                  </span>
                  <ul className="space-y-1 text-slate-300 list-disc list-inside">
                    {(language === 'ar' ? aiReport.keyFindingsAr : aiReport.keyFindingsEn).map((finding, i) => (
                      <li key={i}>{finding}</li>
                    ))}
                  </ul>
                </div>
              </div>
            ) : (
              <p className="text-[#9fb3c8] text-xs italic">
                {language === 'ar'
                  ? 'اضغط على زر التوليد أعلاه ليقوم Gemini بقراءة وتحليل بيانات التصاريح الحالية وتقديم تقرير تدقيق تنفيذي حقيقي.'
                  : 'Click the button above to have Gemini analyze current live permits and produce an executive audit summary.'}
              </p>
            )}
          </div>

          {/* Standards Cards */}
          <div className="space-y-3">
            <span className="text-xs font-bold text-slate-300 block">
              {language === 'ar' ? 'تفاصيل المعايير القياسية والامتثال:' : 'Evaluated Standards Breakdown:'}
            </span>
            {compliance.standards.map((std) => (
              <div
                key={std.code}
                className="p-4 rounded-xl bg-[#0b1324] border border-[#1c2b4c] hover:border-cyan-500/40 transition space-y-2.5"
              >
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <div className="flex items-center gap-2">
                    <span className="px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 font-mono font-bold text-[11px] border border-cyan-700/50">
                      {std.code}
                    </span>
                    <span className="font-bold text-white text-xs">
                      {language === 'ar' ? std.titleAr : std.titleEn}
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className={`px-2 py-0.5 rounded font-mono text-[10px] font-bold border ${getScoreBadgeColor(std.score)}`}>
                      {language === 'ar' ? std.statusAr : std.status} ({std.score}%)
                    </span>
                  </div>
                </div>

                {/* Progress bar */}
                <div className="w-full bg-[#101b33] rounded-full h-1.5 overflow-hidden">
                  <div
                    className={`h-full transition-all duration-500 ${
                      std.score >= 90 ? 'bg-emerald-400' : std.score >= 70 ? 'bg-amber-400' : 'bg-rose-400'
                    }`}
                    style={{ width: `${std.score}%` }}
                  />
                </div>

                {/* Deficiencies or Gaps */}
                {std.deficienciesEn.length > 0 ? (
                  <div className="p-2.5 rounded bg-rose-950/20 border border-rose-500/30 text-rose-300 space-y-1">
                    <span className="font-bold text-[11px] flex items-center gap-1 text-rose-400">
                      <AlertCircle className="w-3.5 h-3.5" />
                      {language === 'ar' ? 'نقاط عدم الامتثال المرصودة:' : 'Identified Non-Compliance Gaps:'}
                    </span>
                    <ul className="list-disc list-inside space-y-0.5 text-[11px]">
                      {(language === 'ar' ? std.deficienciesAr : std.deficienciesEn).map((d, i) => (
                        <li key={i}>{d}</li>
                      ))}
                    </ul>
                  </div>
                ) : (
                  <div className="text-emerald-400 flex items-center gap-1 text-[11px]">
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>
                      {language === 'ar'
                        ? 'كافة الضوابط والمتطلبات مطابقة تماماً للمعيار.'
                        : 'All mandatory controls and verifications satisfied.'}
                    </span>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-[#101b33] border-t border-[#1c2b4c] flex items-center justify-between text-xs">
          <span className="text-[#627d98] font-mono">ZFOD-HSE-AUDIT-2026-LIVE</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-cyan-950 text-cyan-300 hover:bg-cyan-900 border border-cyan-600/40 font-semibold cursor-pointer"
          >
            {language === 'ar' ? 'إغلاق' : 'Close'}
          </button>
        </div>
      </div>
    </div>
  );
};
